import { Brain, Sparkles, Zap, BookOpen, Target, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Link } from "react-router-dom";

const Landing = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="border-b border-border/50 bg-gradient-primary/5">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="rounded-xl bg-gradient-primary p-2 shadow-glow">
                <Brain className="h-6 w-6 text-primary-foreground" />
              </div>
              <h1 className="text-xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                AI Quiz Generator
              </h1>
            </div>
            <Link to="/quiz">
              <Button className="bg-gradient-primary hover:bg-gradient-primary/90 shadow-glow">
                Get Started
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="py-20 bg-gradient-primary/5">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-4xl mx-auto space-y-8">
            <div className="space-y-4">
              <h1 className="text-5xl lg:text-6xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                Master Any Subject with AI-Powered Quizzes
              </h1>
              <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                Transform your learning experience with personalized quizzes generated by artificial intelligence. 
                Choose any topic, select difficulty, and test your knowledge instantly.
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/quiz">
                <Button size="lg" className="bg-gradient-primary hover:bg-gradient-primary/90 shadow-glow text-lg px-8">
                  <Sparkles className="mr-2 h-5 w-5" />
                  Create Your Quiz
                </Button>
              </Link>
              <Button variant="outline" size="lg" className="text-lg px-8">
                <BookOpen className="mr-2 h-5 w-5" />
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-4xl font-bold">Why Choose AI Quiz Generator?</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Leverage the power of AI to create engaging, personalized learning experiences
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="border-primary/20 shadow-glow bg-gradient-primary/5">
              <CardHeader className="text-center">
                <div className="rounded-full bg-gradient-primary p-3 w-fit mx-auto">
                  <Zap className="h-6 w-6 text-primary-foreground" />
                </div>
                <CardTitle>Instant Generation</CardTitle>
                <CardDescription>
                  Generate comprehensive quizzes in seconds on any topic you can imagine
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• AI-powered question creation</li>
                  <li>• Multiple choice formats</li>
                  <li>• Unlimited topics</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-primary/20 shadow-glow bg-gradient-primary/5">
              <CardHeader className="text-center">
                <div className="rounded-full bg-gradient-primary p-3 w-fit mx-auto">
                  <Target className="h-6 w-6 text-primary-foreground" />
                </div>
                <CardTitle>Adaptive Difficulty</CardTitle>
                <CardDescription>
                  Choose from easy, medium, or hard difficulty levels to match your learning needs
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• Beginner-friendly options</li>
                  <li>• Advanced challenges</li>
                  <li>• Progressive learning</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-primary/20 shadow-glow bg-gradient-primary/5">
              <CardHeader className="text-center">
                <div className="rounded-full bg-gradient-primary p-3 w-fit mx-auto">
                  <Star className="h-6 w-6 text-primary-foreground" />
                </div>
                <CardTitle>Smart Analytics</CardTitle>
                <CardDescription>
                  Get detailed performance insights and track your learning progress over time
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• Detailed scorecards</li>
                  <li>• Performance tracking</li>
                  <li>• Time-based metrics</li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-primary/10">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-2xl mx-auto space-y-6">
            <h2 className="text-4xl font-bold">Ready to Start Learning?</h2>
            <p className="text-xl text-muted-foreground">
              Join thousands of learners who are already using AI to enhance their knowledge
            </p>
            <Link to="/quiz">
              <Button size="lg" className="bg-gradient-primary hover:bg-gradient-primary/90 shadow-glow text-lg px-8">
                <Brain className="mr-2 h-5 w-5" />
                Start Your First Quiz
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 py-8">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-gradient-primary p-1.5">
                <Brain className="h-4 w-4 text-primary-foreground" />
              </div>
              <span className="font-semibold">AI Quiz Generator</span>
            </div>
            <p className="text-sm text-muted-foreground">
              Powered by Google Gemini AI
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;