// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heglwifgpffidrzhsqgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZ2x3aWZncGZmaWRyemhzcWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTI4NzUsImV4cCI6MjA3MzIyODg3NX0.WXckaZn13AeVJWmAWR4WuKTuZ9l53bds_PZpmxt55d4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});